### ISSUE TITLE
Low accuracy on ImageNet1K validation

### ISSUE THREAD

**Issue by app2scale** [bamps53/convnext-tf#3]
I'm using your TF-converted model (tiny) and testing on ImageNet 1K validation images, but I'm getting 78% accuracy instead of the officially published 82%. 

Do you think that a 4 percent drop could be because of Torch/Tensorflow difference? Another converted model (https://github.com/sayakpaul/ConvNeXt-TF) attains 81% and the only difference between you and sayakpaul is the implementation of depthwise convolution.   Have you tested your model on validation and if so, can you share the steps so that I could figure out the problem?

**Comment by app2scale** [comment]
It turns out that, I had a mistake in the order of pooling and normalization layer in the head. Now I obtain the 81% val accuracy as indicated in sayakpaul's repo.

By the way, I think your converted model is more flexible than sayakpaul's. His model uses grouped convolution feature in Depthwise Conv layer which can run only on GPU.

**Comment by bamps53** [comment]
Thanks for investigating and reporting it!
Good to know I haven't spread a garbage weight:)
